AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Collect and send logs from Akamai DataStream API to Coralogix.
Metadata:
  AWS::ServerlessRepo::Application:
    Name: Coralogix-Akamai-DataStream
    Description: Collect and send logs from Akamai DataStream API to Coralogix.
    Author: Coralogix
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels:
      - coralogix
      - logs
      - akamai
      - datastream
      - api
    HomePageUrl: https://coralogix.com
    SemanticVersion: 1.0.6
    SourceCodeUrl: https://github.com/coralogix/coralogix-aws-serverless
Parameters:
  CoralogixRegion:
    Type: String
    Description: The Coralogix location region, possible options are [Europe, Europe2, India, Singapore, US]
    AllowedValues:
      - Europe
      - Europe2
      - India
      - Singapore
      - US
    Default: Europe
  PrivateKey:
    Type: String
    Description: The Coralogix private key which is used to validate your authenticity
    AllowedPattern: '[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}'
    ConstraintDescription: The PrivateKey should be valid UUID string
    MinLength: 36
    MaxLength: 36
    NoEcho: true
  ApplicationName:
    Type: String
    Description: The name of your application
    MinLength: 1
    MaxLength: 64
    Default: Akamai
  SubsystemName:
    Type: String
    Description: The subsystem name of your application
    MinLength: 1
    MaxLength: 64
    Default: DataStream
  FunctionArchitecture:
    Type: String
    Description: Lambda function architecture, possible options are [x86_64, arm64]
    AllowedValues:
      - x86_64
      - arm64
    Default: x86_64
  FunctionMemorySize:
    Type: Number
    Description: Lambda function memory limit
    MinValue: 128
    MaxValue: 3008
    Default: 1024
  FunctionTimeout:
    Type: Number
    Description: Lambda function timeout limit
    MinValue: 30
    MaxValue: 900
    Default: 300
  Schedule:
    Type: String
    Description: Akamai DataStream API pulling schedule
    MinLength: 3
    MaxLength: 320
    Default: 'rate(5 minutes)'
  Enabled:
    Type: String
    Description: Akamai DataStream API pulling state
    AllowedValues:
      - True
      - False
    Default: True
  NotificationEmail:
    Type: String
    Description: Failure notification email address
    MaxLength: 320
    Default: ''
  AkamaiHost:
    Type: String
    Description: Akamai API Host
    MinLength: 1
    MaxLength: 255
  AkamaiClientToken:
    Type: String
    Description: Akamai API Client Token
    MinLength: 1
    MaxLength: 64
    NoEcho: true
  AkamaiClientSecret:
    Type: String
    Description: Akamai API Client Secret
    MinLength: 1
    MaxLength: 64
    NoEcho: true
  AkamaiAccessToken:
    Type: String
    Description: Akamai API Access Token
    MinLength: 1
    MaxLength: 64
    NoEcho: true
  AkamaiDataStreamID:
    Type: Number
    Description: Akamai DataStream ID
    MinValue: 1
  AkamaiDataStreamLogsType:
    Type: String
    Description: Akamai DataStream logs type
    AllowedValues:
      - raw-logs
      - aggregate-logs
    Default: raw-logs
  AkamaiDataStreamMaxRecordsLimit:
    Type: Number
    Description: Akamai DataStream API request max records limit
    MinValue: 1
    MaxValue: 10000
    Default: 2000
Mappings:
  CoralogixRegionMap:
    Europe:
      LogUrl: https://api.coralogix.com/api/v1/logs
    Europe2:
      LogUrl: https://api.eu2.coralogix.com/api/v1/logs
    India:
      LogUrl: https://api.app.coralogix.in/api/v1/logs
    Singapore:
      LogUrl: https://api.coralogixsg.com/api/v1/logs
    US:
      LogUrl: https://api.coralogix.us/api/v1/logs
Conditions:
  IsNotificationEnabled:
    Fn::Not:
      - Fn::Equals:
          - Ref: NotificationEmail
          - ''
Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Collect and send logs from Akamai DataStream API to Coralogix.
      CodeUri: .
      Handler: index.handler
      Runtime: nodejs12.x
      Architectures:
        - Ref: FunctionArchitecture
      MemorySize:
        Ref: FunctionMemorySize
      Timeout:
        Ref: FunctionTimeout
      Environment:
        Variables:
          CORALOGIX_URL:
            Fn::FindInMap:
              - CoralogixRegionMap
              - Ref: CoralogixRegion
              - LogUrl
          CORALOGIX_PRIVATE_KEY:
            Ref: PrivateKey
          CORALOGIX_APP_NAME:
            Ref: ApplicationName
          CORALOGIX_SUB_SYSTEM:
            Ref: SubsystemName
          AKAMAI_HOST:
            Ref: AkamaiHost
          AKAMAI_CLIENT_TOKEN:
            Ref: AkamaiClientToken
          AKAMAI_CLIENT_SECRET:
            Ref: AkamaiClientSecret
          AKAMAI_ACCESS_TOKEN:
            Ref: AkamaiAccessToken
          AKAMAI_STREAM_ID:
            Ref: AkamaiDataStreamID
          AKAMAI_LOGS_TYPE:
            Ref: AkamaiDataStreamLogsType
          AKAMAI_MAX_RECORDS_LIMIT:
            Ref: AkamaiDataStreamMaxRecordsLimit
      Policies:
        - Statement:
            - Sid: LambdaReadOnly
              Effect: Allow
              Action:
                - lambda:GetFunction
                - lambda:ListTags
                - lambda:TagResource
              Resource:
                Fn::Sub: "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:*"
      EventInvokeConfig:
        DestinationConfig:
          OnFailure:
            Type: SNS
      Events:
        CloudWatchSchedule:
          Type: Schedule
          Properties:
            Schedule:
              Ref: Schedule
            Enabled:
              Ref: Enabled

  LambdaFunctionNotificationSubscription:
    Type: AWS::SNS::Subscription
    Condition: IsNotificationEnabled
    Properties:
      Protocol: email
      Endpoint:
        Ref: NotificationEmail
      TopicArn:
        Ref: LambdaFunction.DestinationTopic